In [75]:
# Let printing work the same in Python 2 and 3 - do this if you use python 2
from __future__ import print_function

# NumPy
The NumPy package provides the "ndarray" object. The NumPy array is used to contain data of uniform type with an arbitrary number of dimensions. NumPy then provides basic mathematical and array methods to lay down the foundation for the entire SciPy ecosystem. The following import statement is the generally accepted convention for NumPy.

In [76]:
import numpy as np

## Array Creation
There are several ways to make NumPy arrays. An array has three particular attributes that can be queried: shape, size and the number of dimensions.

### Create an array with one dimension

In [77]:
a = np.array([2, 3, 5, 7, 11])
print("a =")
print(a)
print("a.shape =", a.shape)
print("a.size = ", a.size)
print("a.ndim = ", a.ndim)

a =
[ 2  3  5  7 11]
a.shape = (5,)
a.size =  5
a.ndim =  1


### Create an array with two dimensions

In [78]:
b = np.array([[1, 2], [3, 4], [5, 6]])
print("b =")
print(b)
print("b.shape =", b.shape)
print("b.size = ", b.size)
print("b.ndim = ", b.ndim)

b =
[[1 2]
 [3 4]
 [5 6]]
b.shape = (3, 2)
b.size =  6
b.ndim =  2


### Create an array from a range
  - Integers: use `arange`
  - Real numbers: use `linspace`

In [106]:
x = np.arange(0, 100)
print("x =")
print(x)
print("x.shape =", x.shape)
print("x.size = ", x.size)
print("x.ndim = ", x.ndim)

x =
[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25
 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
 98 99]
x.shape = (98,)
x.size =  98
x.ndim =  1


In [109]:
x2 = np.linspace(0, 1, 11)
print("x2 =")
print(x2)
print("x2.shape =", x2.shape)
print("x2.size = ", x2.size)
print("x2.ndim = ", x2.ndim)

x2 =
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
x2.shape = (11,)
x2.size =  11
x2.ndim =  1


Note that `arange` **excludes** and `linspace` **includes** the uppre limit of the range.

### Create an array with random values

In [80]:
y = np.random.rand(2, 5)
print("y =")
print(y)
print("y.shape =", y.shape)
print("y.size = ", y.size)
print("y.ndim = ", y.ndim)

y =
[[0.77979399 0.20342887 0.20424082 0.60986941 0.98235448]
 [0.42438671 0.72210611 0.8663443  0.45733641 0.70771838]]
y.shape = (2, 5)
y.size =  10
y.ndim =  2


## Array Indexing: 1D arrays

You can get particular elements, or slices of an array. But be careful: **array indices start at 0 in python!**

In [81]:
print("a =")
print(a)

a =
[ 2  3  5  7 11]


### Scalar indexing

In [82]:
print("a[2] = ", a[2])

a[2] =  5


### Slicing

Slice using the range of indices you want - exclusive of the final value, e.g. `a[2:5]` includes indices 2, 3, and 4 **but not index 5**

In [83]:
# Slicing
print(a[2:5])

[ 5  7 11]


## Array Indexing: 2D arrays

In [84]:
print("b = ")
print(b)

b = 
[[1 2]
 [3 4]
 [5 6]]


### Scalar indexing

In [85]:
print("b[0, 0] = ", b[0, 0])
print("b[2, 1] = ", b[2, 1])

b[0, 0] =  1
b[2, 1] =  6


### Slicing

In [86]:
print("b[:,0] = ", b[:, 0])
print("b[1,:] = ", b[1, :])

b[:,0] =  [1 3 5]
b[1,:] =  [3 4]


In [87]:
print("b[0:2, :] = \n", b[0:2, :])

b[0:2, :] = 
 [[1 2]
 [3 4]]


## Array math

In [88]:
a1 = np.array([1, 2, 3])
a2 = np.array([5, 10, 15])
print("a1 = \n", a1)
print("a2 = \n", a2)

a1 = 
 [1 2 3]
a2 = 
 [ 5 10 15]


Mathematics is done **element wise**

In [89]:
print("Multiplication: a1*a2 = \n", a1*a2)
print("Division: a1/a2 = \n", a1/a2)
print("Exponents: a1**2 = \n", a1**2)

Multiplication: a1*a2 = 
 [ 5 20 45]
Division: a1/a2 = 
 [0.2 0.2 0.2]
Exponents: a1**2 = 
 [1 4 9]


If the array sizes do not match, get an error.

In [90]:
a3 = np.array([1, 2])
a1*a3

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

Multiplication by a constant

In [91]:
c = 2
print("const*a1 = \n", c*a1)

const*a1 = 
 [2 4 6]


Other mathematics functions included in numpy:
 - Trigonometric functions (e.g. `np.tan(x)`)
 - Exponentials and logs: `np.exp(x)`, `np.log`
 - $\sqrt{x}$: `np.sqrt(x)`

In [105]:
print("a1 =", a1)
print("np.sin(a1*np.pi/2) = ", np.sin(a1*np.pi/2))
print("np.exp(a1) = ", np.exp(a1))
print("np.sqrt(a1) = ", np.sqrt(a1))

a1 = [1 2 3]
np.sin(a1*np.pi/2) =  [ 1.0000000e+00  1.2246468e-16 -1.0000000e+00]
np.exp(a1) =  [ 2.71828183  7.3890561  20.08553692]
np.sqrt(a1) =  [1.         1.41421356 1.73205081]


### Matrix algebra: use `dot`

In [70]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]])
print("m1 =\n", m1)
print("m2 = \n", m2)

m1 =
 [[1 2]
 [3 4]]
m2 = 
 [[0.1 0.2 0.3]
 [0.4 0.5 0.6]]


In [72]:
print("np.dot(m1, m2) = \n", np.dot(m1, m2))

np.dot(m1, m2) = 
 [[0.9 1.2 1.5]
 [1.9 2.6 3.3]]


The dimensionality rules of matrix multiplication apply when using dot on 2D arrays:

In [73]:
np.dot(m2, m1)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)